---
- hosts: all
  remote_user: root
  max_fail_percentage: 0
  serial: "{{ serial_count }}"
  gather_facts: "{{ is_gather_facts }}"
  vars:
    service_sign: "{{ service_sign }}"

  tasks:
  - name: "{{ artifact_typ }}"
    include_tasks: "{{ artifact_typ }}/main.yml"
